/* eslint-disable no-magic-numbers */
import { range, map } from '@laufire/utils/collection';
import { rndBetween, rndString } from '@laufire/utils/random';

const config = {
	barChartProps: {
		width: 300,
		height: 300,
		margin: {
			bottom: 30,
			left: 55,
			top: 10,
			right: 10,
		},
		xScale: {
			padding: 0.2,
		},
		subBarPadding: 0.05,
		duration: 1000,
		delay: 100,
	},
	barAndLineChartProps: {
		width: 300,
		height: 300,
		margin: {
			bottom: 30,
			left: 55,
			top: 10,
			right: 10,
		},
		xScale: {
			padding: 0.3,
		},
		lineStrokeWidth: 3,
		duration: 1000,
		delay: 100,
	},
	pieChartProps: {
		width: 500,
		height: 500,
		margin: 150,
		radius: {
			outer: 150,
			inner: 60,
		},
		pieFill: '#8884d8',
		labelFill: '#fff',
	},
	product: [
		{
			product: 'orange',
			weekOne: 10,
			weekTwo: 200,
			weekThree: 45,
		},
		{
			product: 'apple',
			weekOne: 30,
			weekTwo: 80,
			weekThree: 45,
		},
		{
			product: 'grape',
			weekOne: 15,
			weekTwo: 54,
			weekThree: 45,
		},
	],
	market: [
		{
			product: 'carrot',
			sold: 120,
		},
		{
			product: 'cabbage',
			sold: 30,
		},
		{
			product: 'tomato',
			sold: 65,
		},
	],

	population: map(range(0, 8), () => ({
		country: rndString(),
		population: rndBetween(0, 60),
	})),

	radarChartOptions: {
		width: 350,
		height: 350,
		margin: { top: 20, right: 30, bottom: 20, left: 30 },
		levels: 5,
		maxValue: 0.5,
		labelFactor: 1.25,
		wrapWidth: 60,
		opacityArea: 0.35,
		dotRadius: 4,
		opacityCircles: 0.1,
		strokeWidth: 2,
		roundStrokes: true,
	},

	smartPhones: [
		{
			name: 'iPhone',
			axes: [
				{ axis: 'Battery Life', value: 0.22 },
				{ axis: 'Brand', value: 0.28 },
				{ axis: 'Contract Cost', value: 0.29 },
				{ axis: 'Design And Quality', value: 0.17 },
				{ axis: 'Have Internet Connectivity', value: 0.22 },
				{ axis: 'Large Screen', value: 0.02 },
				{ axis: 'Price Of Device', value: 0.21 },
				{ axis: 'To Be A Smartphone', value: 0.50 },
			],
		},
		{ name: 'Samsung',
			axes: [
				{ axis: 'Battery Life', value: 0.27 },
				{ axis: 'Brand', value: 0.16 },
				{ axis: 'Contract Cost', value: 0.35 },
				{ axis: 'Design And Quality', value: 0.13 },
				{ axis: 'Have Internet Connectivity', value: 0.20 },
				{ axis: 'Large Screen', value: 0.13 },
				{ axis: 'Price Of Device', value: 0.35 },
				{ axis: 'To Be A Smartphone', value: 0.38 },
			] },
		{
			name: 'Nokia',
			axes: [
				{ axis: 'Battery Life', value: 0.26 },
				{ axis: 'Brand', value: 0.10 },
				{ axis: 'Contract Cost', value: 0.30 },
				{ axis: 'Design And Quality', value: 0.14 },
				{ axis: 'Have Internet Connectivity', value: 0.22 },
				{ axis: 'Large Screen', value: 0.04 },
				{ axis: 'Price Of Device', value: 0.41 },
				{ axis: 'To Be A Smartphone', value: 0.30 },
			],
		},
	],

	heatMapProps: {
		width: 450,
		height: 450,
		margin: {
			top: 30,
			bottom: 30,
			left: 30,
			right: 30,
		},
		colorRange: ['#dadada', '#ff776e'],
		padding: 0.05,
	},
	heatMapData: [
		{ group: 'A', variable: 'v1', value: 30 },
		{ group: 'A', variable: 'v2', value: 95 },
		{ group: 'A', variable: 'v3', value: 22 },
		{ group: 'A', variable: 'v4', value: 14 },
		{ group: 'A', variable: 'v5', value: 59 },
		{ group: 'A', variable: 'v6', value: 52 },
		{ group: 'A', variable: 'v7', value: 88 },
		{ group: 'A', variable: 'v8', value: 20 },
		{ group: 'A', variable: 'v9', value: 99 },
		{ group: 'A', variable: 'v10', value: 66 },
		{ group: 'B', variable: 'v1', value: 37 },
		{ group: 'B', variable: 'v2', value: 50 },
		{ group: 'B', variable: 'v3', value: 81 },
		{ group: 'B', variable: 'v4', value: 79 },
		{ group: 'B', variable: 'v5', value: 84 },
		{ group: 'B', variable: 'v6', value: 91 },
		{ group: 'B', variable: 'v7', value: 82 },
		{ group: 'B', variable: 'v8', value: 89 },
		{ group: 'B', variable: 'v9', value: 6 },
		{ group: 'B', variable: 'v10', value: 10 },
		{ group: 'C', variable: 'v1', value: 96 },
		{ group: 'C', variable: 'v2', value: 13 },
		{ group: 'C', variable: 'v3', value: 98 },
		{ group: 'C', variable: 'v4', value: 10 },
		{ group: 'C', variable: 'v5', value: 86 },
		{ group: 'C', variable: 'v6', value: 23 },
		{ group: 'C', variable: 'v7', value: 74 },
		{ group: 'C', variable: 'v8', value: 47 },
		{ group: 'C', variable: 'v9', value: 73 },
		{ group: 'C', variable: 'v10', value: 0 },
		{ group: 'D', variable: 'v1', value: 75 },
		{ group: 'D', variable: 'v2', value: 18 },
		{ group: 'D', variable: 'v3', value: 92 },
		{ group: 'D', variable: 'v4', value: 43 },
		{ group: 'D', variable: 'v5', value: 16 },
		{ group: 'D', variable: 'v6', value: 27 },
		{ group: 'D', variable: 'v7', value: 76 },
		{ group: 'D', variable: 'v8', value: 24 },
		{ group: 'D', variable: 'v9', value: 1 },
		{ group: 'D', variable: 'v10', value: 0 },
		{ group: 'E', variable: 'v1', value: 44 },
		{ group: 'E', variable: 'v2', value: 29 },
		{ group: 'E', variable: 'v3', value: 58 },
		{ group: 'E', variable: 'v4', value: 55 },
		{ group: 'E', variable: 'v5', value: 65 },
		{ group: 'E', variable: 'v6', value: 56 },
		{ group: 'E', variable: 'v7', value: 9 },
		{ group: 'E', variable: 'v8', value: 78 },
		{ group: 'E', variable: 'v9', value: 49 },
		{ group: 'E', variable: 'v10', value: 0 },
		{ group: 'F', variable: 'v1', value: 35 },
		{ group: 'F', variable: 'v2', value: 80 },
		{ group: 'F', variable: 'v3', value: 8 },
		{ group: 'F', variable: 'v4', value: 46 },
		{ group: 'F', variable: 'v5', value: 48 },
		{ group: 'F', variable: 'v6', value: 100 },
		{ group: 'F', variable: 'v7', value: 17 },
		{ group: 'F', variable: 'v8', value: 41 },
		{ group: 'F', variable: 'v9', value: 33 },
		{ group: 'F', variable: 'v10', value: 0 },
		{ group: 'G', variable: 'v1', value: 77 },
		{ group: 'G', variable: 'v2', value: 62 },
		{ group: 'G', variable: 'v3', value: 94 },
		{ group: 'G', variable: 'v4', value: 15 },
		{ group: 'G', variable: 'v5', value: 69 },
		{ group: 'G', variable: 'v6', value: 63 },
		{ group: 'G', variable: 'v7', value: 61 },
		{ group: 'G', variable: 'v8', value: 54 },
		{ group: 'G', variable: 'v9', value: 38 },
		{ group: 'G', variable: 'v10', value: 0 },
		{ group: 'H', variable: 'v1', value: 39 },
		{ group: 'H', variable: 'v2', value: 26 },
		{ group: 'H', variable: 'v3', value: 90 },
		{ group: 'H', variable: 'v4', value: 83 },
		{ group: 'H', variable: 'v5', value: 31 },
		{ group: 'H', variable: 'v6', value: 2 },
		{ group: 'H', variable: 'v7', value: 51 },
		{ group: 'H', variable: 'v8', value: 28 },
		{ group: 'H', variable: 'v9', value: 42 },
		{ group: 'H', variable: 'v10', value: 0 },
		{ group: 'I', variable: 'v1', value: 5 },
		{ group: 'I', variable: 'v2', value: 60 },
		{ group: 'I', variable: 'v3', value: 21 },
		{ group: 'I', variable: 'v4', value: 25 },
		{ group: 'I', variable: 'v5', value: 3 },
		{ group: 'I', variable: 'v6', value: 70 },
		{ group: 'I', variable: 'v7', value: 34 },
		{ group: 'I', variable: 'v8', value: 68 },
		{ group: 'I', variable: 'v9', value: 57 },
		{ group: 'I', variable: 'v10', value: 0 },
		{ group: 'J', variable: 'v1', value: 19 },
		{ group: 'J', variable: 'v2', value: 85 },
		{ group: 'J', variable: 'v3', value: 53 },
		{ group: 'J', variable: 'v4', value: 45 },
		{ group: 'J', variable: 'v5', value: 71 },
		{ group: 'J', variable: 'v6', value: 64 },
		{ group: 'J', variable: 'v7', value: 4 },
		{ group: 'J', variable: 'v8', value: 12 },
		{ group: 'J', variable: 'v9', value: 97 },
		{ group: 'J', variable: 'v10', value: 0 },
	],
};

export default config;
